from enum import Enum


class BuildingOccupancy(Enum):
    EDUCATIONAL = 0
    RESIDENTIAL = 1
    RELIGIONAL = 2
    MEDICAL = 3
    INDUSTRIAL = 4
    EMERGENCY = 5
    COMMERCIAL = 6


class BuildingFramework(Enum):
    CONCRETE_FRAME_WITH_UNREINFORCED_MASONRY_INFILL_WALLS = 0
    CONCRETE_MOMENT_FRAME = 1
    CONCRETE_SHEAR_WALLS = 2
    MOBILE_HOMES = 3
    PRECAST_CONCRETE_FRAMES_WITH_CONCRETE_SHEAR_WALLS = 4
    PRECAST_CONCRETE_TILT_UP_WALLS = 5
    REINFORCED_MASONRY_BEARING_WALLS_WITH_PRECAST_CONCRETE_DIAPHRAGMS = 6
    REINFORCED_MASONRY_BEARING_WALLS_WITH_WOOD_OR_METAL_DECK_DIAPHRAGMS = 7
    STEEL_BRACED_FRAME = 8
    STEEL_FRAME_WITH_CAST_IN_PLACE_CONCRETE_SHEAR_WALLS = 9
    STEEL_FRAME_WITH_UNREINFORCED_MASONRY_INFILL_WALLS = 10
    STEEL_LIGHT_FRAME = 11
    STEEL_MOMENT_FRAME = 12
    UNREINFORCED_MASONRY_BEARING_WALLS = 13
    WOOD_COMMERCIAL_AND_INDUSTRIAL_OVER_5000_SQ_FT = 14
    WOOD_LIGHT_FRAME_UNDER_5000_SQ_FT = 15

